title: Kyoungsup shin
description: Data analyst & AI application @ Hanwha Solution (2018 ~ )
site_title: '@portfolio - Kyoungsup shin'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization/workspaces/portfolio/vendor
github_username: kyoungsup.shin
blog_url: https://kyoungsupshin.github.io/portfolio/
email: sks8803@gmail.com


# absolute or relative
profile_picture: assets/images/IMG_4030.jpg

# Google Analytics ID
google_analytics: 